# -*- coding: utf-8 -*-
"""
/***************************************************************************
 renderUP
                                 A QGIS plugin
 编制方案渲染出图工具
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-28
        copyright            : (C) 2023 by mono zou
        email                : zou_mono@sina.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load renderUP class from file renderUP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .renderUP import renderUP
    return renderUP(iface)
